name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Get Site Path
        id: site-path
        run: |
          SITE_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")
          echo "path=$SITE_PATH"
          echo "path=$SITE_PATH" >> $GITHUB_OUTPUT
          ls -Flatr $SITE_PATH
      - name: Cache Torch
        id: cache-torch
        uses: actions/cache@v5
        with:
          path: ${{ steps.site-path.outputs.path }}
          key: ${{ runner.os }}-pip-torch
      - name: Install Torch
        if: steps.cache-torch.outputs.cache-hit != 'true'
        run: |
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

          TORCH_PATH=$(python -c 'import torch; import os; print(os.path.dirname(torch.__file__))')
          
          echo "LIBTORCH=$TORCH_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$TORCH_PATH/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV

          lf -Flatr ${{ steps.site-path.outputs.path }}
      - name: Build
        run: cargo build --all --verbose
      - name: Run tests
        run: cargo test --all --verbose
